### ISSUE TITLE
Restart loop detected -> Adapter stopped working

### ISSUE THREAD

**Issue by UlliMUC** [PLCHome/ioBroker.growatt#24]
**Describe your inverter**

Typ, modell, ...
The enviroment (panels, accu etc.)
The modell of the logger

**Describe the bug**  
Since a few weeks the message "An adapter instance crashes frequently at startup and was stopped for this reason. The log file must be checked before restarting the instance."

**To Reproduce**  
...

**Expected behavior**  
...

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/78802971/165241125-1d03a946-7c5d-4d3c-bcb9-c8b40585583d.png)

**Versions:**

- Adapter version: 1.1.13
- JS-Controller version: 3.3.19
- Node version: v14.18.1
- Operating system: linux

**Additional context**  
Logfile from yesterday:
`2022-04-25 00:00:00.042 - info: sourceanalytix.0 (24936) Reset start values for : growatt.0.596464.devices.GAH0A4404V.deviceData.eToday
2022-04-25 00:00:00.076 - info: sourceanalytix.0 (24936) Memory values before reset : {"stateDetails":{"alias":"","consumption":false,"costs":true,"deviceName":"growatt__0__596464__devices__GAH0A4404V__deviceData__eToday","financialCategory":"costs","headCategory":"consumed","meter_values":false,"name":"eToday","stateType":"ElectricityDay","stateUnit":"W","useUnit":"kWh"},"calcValues":{"start_day":4.541879066556176,"start_month":4.107167118639509,"start_quarter":4.107167118639509,"start_week":4.362427721195068,"start_year":3.1692590253338797,"valueAtDeviceInit":null,"valueAtDeviceReset":null,"cumulativeValue":4.5500703593339535,"previousReadingWatt":0.8,"previousReadingWattTs":1650837577532},"prices":{"basicPrice":"15","unitPrice":"0.27"}}
2022-04-25 00:00:00.214 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.previousWeek.07_Sunday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.261 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.currentWeek.07_Sunday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.282 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.previousWeek.01_Monday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.291 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.currentWeek.01_Monday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.314 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.previousWeek.02_Tuesday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.361 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.currentWeek.02_Tuesday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.381 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.previousWeek.03_Wednesday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.430 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.currentWeek.03_Wednesday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.448 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.previousWeek.04_Thursday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.455 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.currentWeek.04_Thursday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.482 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.previousWeek.05_Friday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.531 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.currentWeek.05_Friday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.549 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.previousWeek.06_Saturday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.556 - warn: sourceanalytix.0 (24936) State "sourceanalytix.0.growatt__0__596464__devices__GAH0A4404V__deviceData__eToday.currentYear.meterReadings.currentWeek.06_Saturday" has no existing object, this might lead to an error in future versions
2022-04-25 00:00:00.585 - info: sourceanalytix.0 (24936) Memory values after reset : {"stateDetails":{"alias":"","consumption":false,"costs":true,"deviceName":"growatt__0__596464__devices__GAH0A4404V__deviceData__eToday","financialCategory":"costs","headCategory":"consumed","meter_values":false,"name":"eToday","stateType":"ElectricityDay","stateUnit":"W","useUnit":"kWh"},"calcValues":{"start_day":4.5500703593339535,"start_month":4.107167118639509,"start_quarter":4.107167118639509,"start_week":4.5500703593339535,"start_year":3.1692590253338797,"valueAtDeviceInit":null,"valueAtDeviceReset":null,"cumulativeValue":4.5500703593339535},"prices":{"basicPrice":"15","unitPrice":"0.27"}}
2022-04-25 00:00:00.586 - info: sourceanalytix.0 (24936) Current value of state : {"val":0.8,"ack":true,"ts":1650837577532,"q":0,"from":"system.adapter.growatt.0","user":"system.user.admin","lc":1650814228270}
2022-04-25 16:03:09.259 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:03:22.872 - warn: growatt.0 (25959) Growatt login: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:05:58.297 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:07:44.956 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:08:29.542 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:09:04.758 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:09:42.355 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:27:19.228 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:38:26.666 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:40:32.176 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:41:12.454 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:45:49.763 - info: growatt.0 (25959) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 16:54:46.020 - error: growatt.0 (25959) Growatt exception: Error: timeout of 60000ms exceeded
2022-04-25 16:54:46.028 - error: growatt.0 (25959) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-25 16:54:46.028 - error: growatt.0 (25959) unhandled promise rejection: Cannot read property 'captureException' of undefined
2022-04-25 16:54:46.029 - error: growatt.0 (25959) TypeError: Cannot read property 'captureException' of undefined
at Growatt.growattData (/opt/iobroker/node_modules/iobroker.growatt/growattMain.js:354:45)
2022-04-25 16:54:46.030 - error: growatt.0 (25959) Cannot read property 'captureException' of undefined
2022-04-25 16:54:46.036 - info: growatt.0 (25959) terminating
2022-04-25 16:54:46.038 - warn: growatt.0 (25959) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-25 16:54:46.668 - error: host.ioBroker instance system.adapter.growatt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-04-25 16:54:46.673 - info: host.ioBroker Restart adapter system.adapter.growatt.0 because enabled
2022-04-25 16:55:16.751 - info: host.ioBroker instance system.adapter.growatt.0 started with pid 28931
2022-04-25 16:55:18.408 - info: growatt.0 (28931) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2022-04-25 16:55:18.491 - info: growatt.0 (28931) starting. Version 1.1.13 in /opt/iobroker/node_modules/iobroker.growatt, node: v14.18.1, js-controller: 3.3.19
2022-04-25 16:56:13.247 - info: growatt.0 (28931) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 17:16:15.660 - info: growatt.0 (28931) Growatt relogin on session failed: Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
2022-04-25 21:05:46.247 - error: growatt.0 (28931) Growatt exception: Error: timeout of 60000ms exceeded
2022-04-25 21:05:46.269 - error: growatt.0 (28931) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-25 21:05:46.270 - error: growatt.0 (28931) unhandled promise rejection: Cannot read property 'captureException' of undefined
2022-04-25 21:05:46.272 - error: growatt.0 (28931) TypeError: Cannot read property 'captureException' of undefined
at Growatt.growattData (/opt/iobroker/node_modules/iobroker.growatt/growattMain.js:354:45)
2022-04-25 21:05:46.273 - error: growatt.0 (28931) Cannot read property 'captureException' of undefined
2022-04-25 21:05:46.290 - info: growatt.0 (28931) terminating
2022-04-25 21:05:46.293 - warn: growatt.0 (28931) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-25 21:05:46.924 - error: host.ioBroker instance system.adapter.growatt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-04-25 21:05:46.928 - info: host.ioBroker Restart adapter system.adapter.growatt.0 because enabled
2022-04-25 21:06:17.001 - info: host.ioBroker instance system.adapter.growatt.0 started with pid 6509
2022-04-25 21:06:18.757 - info: growatt.0 (6509) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2022-04-25 21:06:18.821 - info: growatt.0 (6509) starting. Version 1.1.13 in /opt/iobroker/node_modules/iobroker.growatt, node: v14.18.1, js-controller: 3.3.19
2022-04-25 21:09:18.956 - error: growatt.0 (6509) Growatt exception: Error: timeout of 60000ms exceeded
2022-04-25 21:09:18.963 - error: growatt.0 (6509) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-25 21:09:18.963 - error: growatt.0 (6509) unhandled promise rejection: Cannot read property 'captureException' of undefined
2022-04-25 21:09:18.964 - error: growatt.0 (6509) TypeError: Cannot read property 'captureException' of undefined
at Growatt.growattData (/opt/iobroker/node_modules/iobroker.growatt/growattMain.js:354:45)
2022-04-25 21:09:18.964 - error: growatt.0 (6509) Cannot read property 'captureException' of undefined
2022-04-25 21:09:18.971 - info: growatt.0 (6509) terminating
2022-04-25 21:09:18.972 - warn: growatt.0 (6509) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-25 21:09:19.586 - error: host.ioBroker instance system.adapter.growatt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-04-25 21:09:19.591 - info: host.ioBroker Restart adapter system.adapter.growatt.0 because enabled
2022-04-25 21:09:49.634 - info: host.ioBroker instance system.adapter.growatt.0 started with pid 7015
2022-04-25 21:09:51.293 - info: growatt.0 (7015) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2022-04-25 21:09:51.351 - info: growatt.0 (7015) starting. Version 1.1.13 in /opt/iobroker/node_modules/iobroker.growatt, node: v14.18.1, js-controller: 3.3.19
2022-04-25 21:11:21.485 - error: growatt.0 (7015) Growatt exception: Error: timeout of 60000ms exceeded
2022-04-25 21:11:21.495 - error: growatt.0 (7015) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-25 21:11:21.496 - error: growatt.0 (7015) unhandled promise rejection: Cannot read property 'captureException' of undefined
2022-04-25 21:11:21.497 - error: growatt.0 (7015) TypeError: Cannot read property 'captureException' of undefined
at Growatt.growattData (/opt/iobroker/node_modules/iobroker.growatt/growattMain.js:354:45)
2022-04-25 21:11:21.498 - error: growatt.0 (7015) Cannot read property 'captureException' of undefined
2022-04-25 21:11:21.508 - info: growatt.0 (7015) terminating
2022-04-25 21:11:21.511 - warn: growatt.0 (7015) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-25 21:11:22.177 - error: host.ioBroker instance system.adapter.growatt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-04-25 21:11:22.182 - info: host.ioBroker Restart adapter system.adapter.growatt.0 because enabled
2022-04-25 21:11:22.182 - warn: host.ioBroker Do not restart adapter system.adapter.growatt.0 because restart loop detected
`

**Comment by PLCHome** [comment]
Hello, I'm guessing an expired key. 
The Growatt server refuses the login. However, this can also happen when Growatt is maintaining the server.

Please check login key!

**Comment by UlliMUC** [comment]
Hi, thank you for this quick response! :)

i'm not using a key-login - just username and password:
adapter restart works fine without any issues.
![image](https://user-images.githubusercontent.com/78802971/165255926-11fecb5d-cf1b-402f-939a-fba97168faeb.png)

**Comment by PLCHome** [comment]
I reformatted the log, this is interesting:

```
2022-04-25 16:54:46.020 - error: growatt.0 (25959) Growatt exception: Error: timeout of 60000ms exceeded
2022-04-25 16:54:46.028 - error: growatt.0 (25959) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-25 16:54:46.028 - error: growatt.0 (25959) unhandled promise rejection: Cannot read property 'captureException' of undefined
2022-04-25 16:54:46.029 - error: growatt.0 (25959) TypeError: Cannot read property 'captureException' of undefined at Growatt.growattData (/opt/iobroker/node_modules/iobroker.growatt/growattMain.js:354:45)
2022-04-25 16:54:46.030 - error: growatt.0 (25959) Cannot read property 'captureException' of undefined
```


It must be a problem with the controller

```
        if (sentryInstance) {
          if (!e.toString().toLowerCase().includes('errornologin')) {
            sentryInstance.getSentryObject().captureException(e);
          }
        }
```

SentryInstance exists but getSentryObject() does not return an object.

Is Sentry on or off for you, generally and for the instance?
