### ISSUE TITLE
Adapter objects are no longer updated and are completely gone after a new installation.

### ISSUE THREAD

**Issue by Uwe-Kaki** [PLCHome/ioBroker.growatt#26]
I installed the Growatt ( solar inverter ) adapter to visualize various solar statistics.
 That worked fine until yesterday 7.8.2022 - in the morning I noticed that the object data points are no longer updated, but the solar system / inverter is running, I can see that in the original app.

 So I restarted the instance, logged in again etc, everything is green, only the data updates are not coming.
 Then instance deleted and created again - also nothing.
 Then deleted the aapter and deleted the Growatt object tree, which was then only available at the top level anyway, without relevant data points.

 I then reinstalled the adapter & created a new instance, logged in with user & PW, everything is green, but no data points are created at all now.
 Two weeks ago with the first installation everything went smoothly.

 A) Does anyone know the basic problem that adapters no longer create data points, is that an adapter problem, or is something new in ioBroker?

 b) Does anyone happen to be using the Growatt adapter and is everything still working as expected there?

 IoBroker, adapter etc is all up to date.

The Logfile shows the following:

2022-08-07 20:30:07.732 - info: growatt.0 (1443194) Got terminate signal TERMINATE_YOURSELF
--
2022-08-07 20:30:07.734 - info: host.PI4-Kaki-Home stopInstance system.adapter.growatt.0 send kill signal
2022-08-07 20:30:07.739 - info: growatt.0 (1443194) terminating
2022-08-07 20:30:07.741 - info: growatt.0 (1443194) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-08-07 20:30:08.314 - info: host.PI4-Kaki-Home instance system.adapter.growatt.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-08-07 20:30:08.706 - info: host.PI4-Kaki-Home instance system.adapter.growatt.0 started with pid 1444891
2022-08-07 20:30:10.603 - info: growatt.0 (1444891) starting. Version 1.1.15 in /opt/iobroker/node_modules/iobroker.growatt, node: v14.20.0, js-controller: 4.0.23
2022-08-07 21:14:40.856 - error: growatt.0 (1444891) Growatt exception: Error: Request failed with status code 502

**Comment by Spexx-** [comment]
I have also some problems since yesterday and the adapter don't receive any data. I get following error and warning messages:

Growatt exception: Error: Request failed with status code 588

`Login to share plant:{"message":"Request failed with status code 588","name":"Error","stack":"Error: Request failed with status code 588\n at createError (/opt/iobroker/node_modules/growatt/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/opt/iobroker/node_modules/growatt/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/growatt/node_modules/axios/lib/adapters/http.js:322:11)\n at IncomingMessage.emit (events.js:326:22)\n at endReadableNT (_stream_readable.js:1241:12)\n at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":120000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.26.1"},"baseURL":"https://server.growatt.com","maxRedirects":0,"method":"get","url":"https://server.growatt.com/login/toSharePlant/XXX"},"status":588}`

**Comment by Pandia22** [comment]
The adapter is also not running correctly for me since 07.08.2022.  From time to time data is synchronized.

Error message when logging in with user/password: Growatt exception: Error: Request failed with status code 588

Alternative login with key via URL does not work either. The Growatt server in the web browser can be reached online.

**Comment by PLCHome** [comment]
Yes, I see the problem. I will take care of the remedy as soon as possible.

**Comment by PLCHome** [comment]
version 1.1.16

**Comment by Pandia22** [comment]
Simply updating the adapter was not enough for me. After deleting and reinstalling everything worked.

Thanks for the great support.

**Comment by Uwe-Kaki** [comment]
On my instance still the same : adapter / instance 1.16 running, but no objects are created ( only the top level folders )
Based onprevious comments I de-installed the instance and adapter, ensured the objects are gone as well.
After reinstall, I still get no data.

is there anything else I could do ? Maybe deleting some orphan left overs manually 

here some error I could see : 

2022-08-11 07:43:40.887 - error: host.PI4-Kaki-Home iobroker Error deleting adapter growatt from disk: Cannot find module 'iobroker.growatt/io-package.json'Require stack:- /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js- /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js- /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js
--
2022-08-11 07:43:40.888 - error: host.PI4-Kaki-Home iobroker You might have to delete it yourself!

Connection data point show true, no more errors to see so far.

**Comment by PLCHome** [comment]
So I can't say what happened to you. It looks like something crashed in ioBroker or in the node installation.
I don't understand the message from the ioBroker either. I once had messages like I tried to update my ioBroker instance and the notejs. Luckily not yet under Linux, but there I have everything running in Docker. I am rebuilding the Docker, only the parameterization is outside.

Objects are deleted or not created if the checkboxes in the parameterization are off.

It would be good if you set the adapter to silly and post the log. But please be careful not to post any passwords, users or keys here. they can be in the log.

**Comment by santacrews** [comment]
Same here. No updates since 3 days. Simply updated to 1.16 without success. Deleted Adapter and installed new, unfortunately again without connection after installation.

**Comment by PLCHome** [comment]
There was a general problem with the Growatt website. There seems to be a second problem here.

Since it seems to run error-free for some others, there must be another reason for you.
All inverter types are queried differently. So at least I have to know the guy. Then I can try to reproduce the error with the demo data of the website.

So, then the standard program to find the error:
**Describe your inverter**

 - Typ, modell, ...
 - The enviroment (panels, accu etc.)
 - The modell of the logger

**Screenshots & Logfiles**  
 - If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**

- Adapter version: <adapter-version>
- JS-Controller version: <js-controller-version> 
- Node version: <node-version> 
- Operating system: <os-name>

**Comment by Spexx-** [comment]
After deleting and reinstalling the adapter it seems to work fine for several hours. But I have received for the second time following error message:

`<html>
<body>


growatt.0 | 2022-08-11 14:01:53.896 | info | starting. Version 1.1.16 in /opt/iobroker/node_modules/iobroker.growatt, node: v12.22.1, js-controller: 4.0.19
-- | -- | -- | --
growatt.0 | 2022-08-11 14:01:53.796 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
host.iobroker | 2022-08-11 14:01:53.239 | info | instance system.adapter.growatt.0 started with pid 31654
host.iobroker | 2022-08-11 14:01:23.205 | info | Restart adapter system.adapter.growatt.0 because enabled
host.iobroker | 2022-08-11 14:01:23.204 | error | instance system.adapter.growatt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
growatt.0 | 2022-08-11 14:01:22.670 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
growatt.0 | 2022-08-11 14:01:22.669 | info | terminating
growatt.0 | 2022-08-11 14:01:22.668 | error | Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle
growatt.0 | 2022-08-11 14:01:22.668 | error | TypeError: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle at JSON.stringify (<anonymous>) at /opt/iobroker/node_modules/growatt/lib/growatt.js:252:45 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5)
growatt.0 | 2022-08-11 14:01:22.668 | error | unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle
growatt.0 | 2022-08-11 14:01:22.666 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`

The adapter is still working and receiving data, so I'm not sure if it will be a problem or not.

**Comment by santacrews** [comment]
@PLCHome 
Thanks for the quick response. Will answer when I am at home. 

Have now used the other solution via "shared key" and this works absolutely fine! So for me it is OK because it is running again, but you might be interested in the cause of my (and others) problem!?
As I said: Will collect data later and share it.

**Comment by PLCHome** [comment]
Converting circular structure to JSON  --> at /opt/iobroker/node_modules/growatt/lib/growatt.js:252:45
ist Fixed
Can you test on unstable?

**Comment by Uwe-Kaki** [comment]
Deleted adapter 1.1.6 and reinstalled 1.1.7.
All looks fine - except not data objects are create.
Only the the top folders Are created, but no data ( see picture )
The logs look ok, nothing strange 

log 
——
2022-08-12 17:22:08.796 - info: growatt.0 (1878342) starting. Version 1.1.17 in /opt/iobroker/node_modules/iobroker.growatt, node: v14.20.0, js-controller: 4.0.23
--
2022-08-12 17:22:08.865 - debug: growatt.0 (1878342) Enter growattData, Param: sessionHold:true
2022-08-12 17:22:08.868 - debug: growatt.0 (1878342) Enter lifeSignCallback 600000ms
2022-08-12 17:22:08.869 - debug: growatt.0 (1878342) Growatt new API
2022-08-12 17:22:08.874 - debug: growatt.0 (1878342) Growatt isConnected() : false
2022-08-12 17:22:08.874 - debug: growatt.0 (1878342) Growatt login with user and password
2022-08-12 17:22:08.876 - debug: growatt.0 (1878342) Enter lifeSignCallback 600000ms
2022-08-12 17:22:09.293 - debug: growatt.0 (1878342) Growatt isConnected() : true
2022-08-12 17:22:09.295 - debug: growatt.0 (1878342) Growatt time for login : 428ms
2022-08-12 17:22:09.297 - debug: growatt.0 (1878342) Enter lifeSignCallback 600000ms
2022-08-12 17:22:09.419 - debug: growatt.0 (1878342) Growatt time for allPlantData : 124ms
2022-08-12 17:22:09.421 - debug: growatt.0 (1878342) Growatt time for parseData : 1ms
2022-08-12 17:22:09.426 - debug: growatt.0 (1878342) Leave growattData :559ms
2022-08-12 17:22:38.867 - debug: growatt.0 (1878342) Enter growattData, Param: sessionHold:true
2022-08-12 17:22:38.869 - debug: growatt.0 (1878342) Enter lifeSignCallback 600000ms
2022-08-12 17:22:38.870 - debug: growatt.0 (1878342) Growatt isConnected() : true
2022-08-12 17:22:38.871 - debug: growatt.0 (1878342) Enter lifeSignCallback 600000ms
2022-08-12 17:22:39.009 - debug: growatt.0 (1878342) Growatt time for allPlantData : 140ms
2022-08-12 17:22:39.010 - debug: growatt.0 (1878342) Growatt time for parseData : 0ms
2022-08-12 17:22:39.011 - debug: growatt.0 (1878342) Leave growattData :142ms
2022-08-12 17:23:08.870 - debug: growatt.0 (1878342) Enter growattData, Param: sessionHold:true
2022-08-12 17:23:08.871 - debug: growatt.0 (1878342) Enter lifeSignCallback 600000ms
2022-08-12 17:23:08.872 - debug: growatt.0 (1878342) Growatt isConnected() : true
2022-08-12 17:23:08.873 - debug: growatt.0 (1878342) Enter lifeSignCallback 600000ms
2022-08-12 17:23:09.007 - debug: growatt.0 (1878342) Growatt time for allPlantData : 136ms
2022-08-12 17:23:09.008 - debug: growatt.0 (1878342) Growatt time for parseData : 0ms
2022-08-12 17:23:09.009 - debug: growatt.0 (1878342) Leave growattData :138ms
————

![61839548-55CF-4D6C-AB3C-7C65040AC0E2](https://user-images.githubusercontent.com/75257707/184388588-5bc8d723-2ce9-4a5f-a833-f3ce012942b2.jpeg)

**Comment by Uwe-Kaki** [comment]
The main settings are all selected, but Objekte Verwalten is empty even after refresh.

**Comment by PLCHome** [comment]
Crazy I'm confused. 
If I understood you correctly, you already had values ​​in the adapter and then reinstalled the adapter. 

Can you still create a second instance?

**Comment by Uwe-Kaki** [comment]
Yes, correct. It did work without issues for some days ( have my solar only since 2 weeks ).
It stopped working until I reported the issue.
I had values and created visualizations in Jarvis, all fine.

I have not tried to create a second instance, will try this and provide feedback.

**Comment by Uwe-Kaki** [comment]
Just created a second instance #1.

same effect, instance is green, but not data points are created.

**Comment by PLCHome** [comment]
I don't understand this at all now.
Can you send me a personal message with a key via the ioBrokerforum.
You get the key when you logon the homepage, go to energy, plant management, share plant on the right.

**Comment by PLCHome** [comment]
![image](https://user-images.githubusercontent.com/29116097/184942793-3a4692b0-5f40-4bdc-b719-077aca51d672.png)

**Comment by Uwe-Kaki** [comment]
Hello, the adapter is now somehow running an reporting values, but since a few days I get lots of this messeges :

growatt.0 | 2022-08-30 09:29:54.988 | error | Growatt exception: AxiosError: Request failed with status code 588
-- | -- | -- | --
growatt.0 | 2022-08-30 09:27:24.619 | error | Growatt exception: TypeError: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle
growatt.0 | 2022-08-30 09:25:24.467 | error | Growatt exception: AxiosError: Request failed with status code 588

The versoin 1.1.17 is installed.

The instance status changes from Green to Yellow on regular basis.

**Comment by smalltower1** [comment]
Hi, I have the same problem as Uwe-Kaki

**Comment by PLCHome** [comment]
Error 588 look at #28
